import { Inter } from 'next/font/google';
import './globals.css';
import StoreProvider from '../redux/StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: "Dim's LOR Vault",
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <StoreProvider>
        {/* suppressHydrationWarning to disable a disable a warning in the browser generated by my ColorZilla extension in dev mode */}
        <body className={inter.className} suppressHydrationWarning={true}>
          {children}
        </body>
      </StoreProvider>
    </html>
  );
}
